spring:
  config:
    import: cadence.yml
  datasource:
    url: jdbc:postgresql://localhost:5434/app
    username: app
    password: app
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  application:
    name: order-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration


logging:
  level:
    root: INFO
    org.hibernate: DEBUG
    org:
      springframework:
        web: DEBUG
server:
  port: 8082


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
app:
  #  audit:
  #    eventDictionary:
  #      1001001: Факт какой-либо внешней, важной, нужной операции
  permit:
    all:
      urls:
        - '/v3/api-docs'
        - '/api/**'